/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MisTramites {
        "image": "";
        "img": "";
        "titulo": '';
        "tramite": any[];
    }
}
declare global {
    interface HTMLMisTramitesElement extends Components.MisTramites, HTMLStencilElement {
    }
    var HTMLMisTramitesElement: {
        prototype: HTMLMisTramitesElement;
        new (): HTMLMisTramitesElement;
    };
    interface HTMLElementTagNameMap {
        "mis-tramites": HTMLMisTramitesElement;
    }
}
declare namespace LocalJSX {
    interface MisTramites {
        "image"?: "";
        "img"?: "";
        "titulo"?: '';
        "tramite"?: any[];
    }
    interface IntrinsicElements {
        "mis-tramites": MisTramites;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mis-tramites": LocalJSX.MisTramites & JSXBase.HTMLAttributes<HTMLMisTramitesElement>;
        }
    }
}
